# Credit Card Fraud Transcation Analysis

In [1]:
# Required python libraries are loaded

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [3]:
#load the dataset to pandas Dataframe
df = pd.read_csv('creditcard.csv')
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,1.341262,0.359894,-0.358091,-0.137134,0.517617,0.401726,-0.058133,0.068653,-0.033194,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,-1.416907,-0.153826,-0.751063,0.167372,0.050144,-0.443587,0.002821,-0.611987,-0.045575,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,-0.619468,0.291474,1.757964,-1.323865,0.686133,-0.076127,-1.222127,-0.358222,0.324505,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,-0.705117,-0.110452,-0.286254,0.074355,-0.328783,-0.210077,-0.499768,0.118765,0.570328,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,1.017614,0.836390,1.006844,-0.443523,0.150219,0.739453,-0.540980,0.476677,0.451773,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
#check missing values in the data set in each column
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
#distribution of Legit and fraudulant transactions
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

# This dataset is highly unbalanced
0--> Normal Transaction
1--> Fraudulant transaction

In [7]:
#separating the Normal and Fradulant transcation to two different variables
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [8]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [9]:
#statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [10]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [11]:
#comparing the values of both transactions
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,0.009824,-0.006576,0.010832,0.000189,0.012064,0.000161,0.007164,0.011535,0.003887,-0.001178,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,-5.676883,3.800173,-6.259393,-0.109334,-6.971723,-0.092929,-4.139946,-6.665836,-2.246308,0.680659,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [12]:
#Undersampling

#Build a sample dataset containing similar distribution of Legit and Fraudulant dataset

#We know that Legit has 284315 data points and Fraud has only 492
#So we will take a random sample of 492 datapoint s from Legit and concatenate with Fraud datapoints
#So that we have equally distributed dataset with both Legit anf Fraud datapoints

legit_sample = legit.sample(n=492)

In [13]:
#concatinate two variables legit_sample nd fraud
df_concat = pd.concat([legit_sample, fraud], axis=0)

In [14]:
df_concat['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [15]:
df_concat.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,95217.949187,0.019670,0.040047,-0.090381,-0.000353,-0.046573,-0.040141,-0.056595,-0.043583,0.009285,-0.071793,-0.066498,0.105183,-0.006476,0.015582,0.059625,0.030840,0.037946,0.013630,-0.016691,-0.005092,-0.011931,-0.047801,-0.024452,-0.021901,0.031630,-0.018163,0.016756,-0.000037,87.933110
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,-5.676883,3.800173,-6.259393,-0.109334,-6.971723,-0.092929,-4.139946,-6.665836,-2.246308,0.680659,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [16]:
df_concat.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
172779,121235.0,0.132489,1.015947,-0.519848,-0.746251,1.179520,-0.301023,0.894987,0.032885,-0.351428,-0.677645,0.769236,0.694092,0.434298,-0.931767,-0.963587,0.609717,-0.038648,0.338815,0.190902,0.067498,-0.308791,-0.750124,0.031311,0.189183,-0.389218,0.115133,0.221448,0.071452,2.28,0
279229,168726.0,-0.091787,0.165854,-0.082205,-3.344551,0.233204,0.537807,-0.963792,-2.493807,1.040143,-2.347706,0.175353,1.687524,0.409174,0.421469,-0.511148,0.711885,-1.302980,0.312177,-0.357684,0.513632,-1.469634,-0.244693,-0.006082,-0.226199,0.502121,-0.721245,0.110329,0.276048,32.36,0
203237,134727.0,0.149965,0.848644,0.057437,0.621198,0.743835,0.186607,0.637625,-0.151240,-0.191415,0.797040,0.428568,-0.788535,-1.668770,0.843128,1.562656,-1.001651,0.020616,1.304391,2.945678,0.317790,0.278200,1.121980,-0.326363,0.300049,-0.437728,0.214999,0.167767,0.025163,1.99,0
210015,137805.0,2.127731,-1.089904,-1.206346,-1.009829,-0.482317,-0.104188,-0.783208,-0.066376,0.025539,0.722297,-1.427531,-0.855028,0.041657,-0.334602,0.201856,1.193940,0.007688,-1.177485,0.765250,0.096921,0.184643,0.442628,0.087002,0.042758,-0.071402,-0.171396,-0.018490,-0.043704,65.00,0
29196,35359.0,0.579988,-1.757091,-0.852842,-0.639489,0.975834,4.000225,-0.762122,0.961973,1.033784,-0.556811,-0.564639,0.409300,-0.022741,-0.331033,-0.068979,0.253557,-0.343690,-0.119796,0.724596,0.769400,-0.071863,-0.906174,-0.268598,1.095571,0.164687,0.919930,-0.098631,0.069443,364.08,0

In [17]:
#splitting the dataset into features nad targets

X = df_concat.drop(columns='Class', axis=1)
Y = df_concat['Class']

In [18]:
print(X.head(5))

            Time        V1        V2        V3        V4        V5        V6  \
172779  121235.0  0.132489  1.015947 -0.519848 -0.746251  1.179520 -0.301023
279229  168726.0 -0.091787  0.165854 -0.082205 -3.344551  0.233204  0.537807
203237  134727.0  0.149965  0.848644  0.057437  0.621198  0.743835  0.186607
210015  137805.0  2.127731 -1.089904 -1.206346 -1.009829 -0.482317 -0.104188
29196    35359.0  0.579988 -1.757091 -0.852842 -0.639489  0.975834  4.000225

              V7        V8        V9       V10       V11       V12       V13  \
172779  0.894987  0.032885 -0.351428 -0.677645  0.769236  0.694092  0.434298
279229 -0.963792 -2.493807  1.040143 -2.347706  0.175353  1.687524  0.409174
203237  0.637625 -0.151240 -0.191415  0.797040  0.428568 -0.788535 -1.668770
210015 -0.783208 -0.066376  0.025539  0.722297 -1.427531 -0.855028  0.041657
29196  -0.762122  0.961973  1.033784 -0.556811 -0.564639  0.409300 -0.022741

             V14       V15       V16       V17       V18       V19       V20  \
172779 -0.931767 -0.963587  0.609717 -0.038648  0.338815  0.190902  0.067498
279229  0.421469 -0.511148  0.711885 -1.302980  0.312177 -0.357684  0.513632
203237  0.843128  1.562656 -1.001651  0.020616  1.304391  2.945678  0.317790
210015 -0.334602  0.201856  1.193940  0.007688 -1.177485  0.765250  0.096921
29196  -0.331033 -0.068979  0.253557 -0.343690 -0.119796  0.724596  0.769400

             V21       V22       V23       V24       V25       V26       V27  \
172779 -0.308791 -0.750124  0.031311  0.189183 -0.389218  0.115133  0.221448
279229 -1.469634 -0.244693 -0.006082 -0.226199  0.502121 -0.721245  0.110329
203237  0.278200  1.121980 -0.326363  0.300049 -0.437728  0.214999  0.167767
210015  0.184643  0.442628  0.087002  0.042758 -0.071402 -0.171396 -0.018490
29196  -0.071863 -0.906174 -0.268598  1.095571  0.164687  0.919930 -0.098631

             V28  Amount
172779  0.071452    2.28
279229  0.276048   32.36
203237  0.025163    1.99
210015 -0.043704   65.00
29196   0.069443  364.08

In [19]:
print(Y.head(5))

172779    0
279229    0
203237    0
210015    0
29196     0
Name: Class, dtype: int64

In [20]:
#splitting the data into training and test data
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, stratify=Y ,random_state=2)

In [21]:
print(X.shape, x_train.shape, x_test.shape)

(984, 30) (787, 30) (197, 30)

In [22]:
#1. Train our data set
#2. Check accuracy
#Logistic Regression
reg = LogisticRegression()

In [23]:
#fit the training data to regression variable
reg.fit(x_train, y_train)

C:\Users\karth\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [24]:
#parse x_train data to predict library and check the accuracy of the prediction
x_train_prediction = reg.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy on Training data:', training_data_accuracy)

Accuracy on Training data: 0.9453621346886912

In [25]:
#check the prediction and accuracy of test data
x_test_prediction = reg.predict(x_test)
testing_data_acccuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy on testing data: ', testing_data_acccuracy)

Accuracy on testing data:  0.9289340101522843

In [26]:
#predictions of the entire train data
reg.predict(x_train)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [27]:
#predictions of the entire test data
reg.predict(x_test)

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0],
      dtype=int64)